### PR TITLE
Issue #66: reset SD on startup for config file parsing

### PR DESCRIPTION
**Pull request by sastel**
@piebrain I think this will fix it though I don't know the procedure to test with the JSON file. Can you explain to me how to do that?

### CODE REVIEW

**Comment by piebrain** [comment]
> @piebrain I think this will fix it though I don't know the procedure to test with the JSON file. Can you explain to me how to do that?

You just copy the default config.json from the project and see if you can use scanning in radio mode.

**Comment by piebrain** [comment]
It is still not loading config.json from SD

**Comment by sastel** [comment]
Works on my machine...
```
   0.         TOP got ENTRY_EVT 
   1.         TOP got START_EVT 
   2.         TOP going to CHARGING  
   3.          ON got ENTRY_EVT 
force slp enable,type: 1
force slp enable,type: 2
fpm open,type:2 0
FILE EXISTS
MIN FREQ: 8800
MAX FREQ: 10800
```

**Comment by sastel** [comment]
@piebrain it is reading the JSON correctly, but it seems that the radio is not scanning. It reports that it scanned but the actual station doesn't change. I'll have to do some more digging to understand why.

**Comment by sastel** [comment]
This is the file that I'm using:
```
sstel@sstel-lt:~/eng/G3-FW[bugfix/ss/issue-66-reset-sd-in-power-up-sequence *$=]
$ cat config.json 
{
    "Main": {
        "RP": "1789",
        "OTASSID": "CompassOTA",
        "OTAPW": "CommitYourWay",
        "USRSSID": "NSA-Van1",
        "USRPW": "BigBrotherWatching"
    },
    "Device": {
        "StartAs": 1,
        "StartFile": "/L1_En_NASB_8sec/S01-Penta/B001_Gen/C001-Gen.mp3",
        "NavigationLevels": 4,
        "FMChannels": "8800:10800",
        "FMDeEmphasis": 50,
        "LoopLang": true,
        "TimeOut": 60,
        "Debug": false
    }
}
```

**Comment by sastel** [comment]
As I scan through all of these stations I hear 94.7 loud and clear:
```
  16.       SLEEP got NAV_RIGHT_BTN_EVT
Channel: 9150
RSSI: 		1 dB
SNR: 		1 dB
  17.       SLEEP going to SLEEP     
  18.       SLEEP got EXIT_EVT  
  19.       SLEEP got ENTRY_EVT 
  20.       SLEEP got START_EVT 
  21.       SLEEP got NAV_RIGHT_BTN_EVT
Channel: 9530
RSSI: 		32 dB
SNR: 		21 dB
  22.       SLEEP going to SLEEP     
  23.       SLEEP got EXIT_EVT  
  24.       SLEEP got ENTRY_EVT 
  25.       SLEEP got START_EVT 
  26.       SLEEP got NAV_RIGHT_BTN_EVT
Channel: 10480
RSSI: 		0 dB
SNR: 		1 dB
  27.       SLEEP going to SLEEP     
  28.       SLEEP got EXIT_EVT  
  29.       SLEEP got ENTRY_EVT 
  30.       SLEEP got START_EVT 
  31.       SLEEP got NAV_RIGHT_BTN_EVT
Channel: 9530
RSSI: 		32 dB
SNR: 		21 dB
  32.       SLEEP going to SLEEP     
  33.       SLEEP got EXIT_EVT  
  34.       SLEEP got ENTRY_EVT 
  35.       SLEEP got START_EVT 
  36.       SLEEP got NAV_RIGHT_BTN_EVT
Channel: 9010
RSSI: 		0 dB
SNR: 		0 dB
  37.       SLEEP going to SLEEP     
  38.       SLEEP got EXIT_EVT  
  39.       SLEEP got ENTRY_EVT 
  40.       SLEEP got START_EVT 
```

**Comment by piebrain** [comment]
I was fooled by the timestamp that prevents copying the file every time

**Review by piebrain — APPROVED** [review]
It works for me now :)

**Pull request merged**
