### PR TITLE
Fix: Device hangs after "readSD()"

### LINKED ISSUE #5: Device hangs after "readSD()"
Device hangs completely once in "readSD()" (can still access the SD card, but device is unresponsive to unplugging cable or power button - have to force power down)

### PR DESCRIPTION
**Pull request by NathanV75**
fixes #5

### CODE REVIEW

**Comment by piebrain** [comment]
Can't get it to work here.

I was trying to debug it and put "ChargingUSB();" just before the unlatch() call and then it seems to work.

@jamesihutton can you chime in here and maybe explain? I would like it to be a stable solution.

**Comment by NathanV75** [comment]
It works fine for me as is. I'm surprised its not working for you.
We could use just "io->OSCIO_set(LOW);" instead which might be better as it avoids resetting the SX1509.
James might know more.

**Comment by jamesihutton** [comment]
Hey guys, this bug seems to have gone away for me. Not sure what caused it that one time a while ago. 
Nathan's suggestion may be more stable in general though. 
Setting the OSCIO to low effectively kills all power to the entire device.

**Comment by piebrain** [comment]
Using "io->OSCIO_set(LOW);" works for me.

@NathanV75 please update your pull request and I will merge it.

Nice work everyone.

**Pull request merged**
